version: '0.9.0.{build}'
os: WMF 5
clone_depth: 10
skip_tags: true

branches:
  only:
  - master
  - develop

install:
  - ps: |
      Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force | Out-Null
      Install-Module InvokeBuild -RequiredVersion 3.2.1 -Scope CurrentUser -Force | Out-Null

build_script:
  - ps: Invoke-Build -Configuration Release

test:
  assemblies:
    - Microsoft.PowerShell.EditorServices.Test.dll
    - Microsoft.PowerShell.EditorServices.Test.Protocol.dll
    - Microsoft.PowerShell.EditorServices.Test.Host.dll

after_test:
  - ps: Invoke-Build UploadTestLogs -Configuration Release