version: '$(core_version).{build}'
os: WMF 5
clone_depth: 10
skip_tags: true

environment:
  core_version: '0.9.0'
  prerelease_name: '-beta'

branches:
  only:
  - master
  - develop

# NOTE: If you need to debug a problem with the AppVeyor build, uncomment the
#       following two lines and push them to your PR branch.  Once the next
#       build starts you will see RDP connection details written out to the
#       build console.  **DON'T FORGET TO REMOVE THIS COMMIT BEFORE MERGING!**

#init:
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# TODO: Work build number into build!

install:
  - ps: |
      Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force | Out-Null
      Install-Module InvokeBuild -RequiredVersion 3.2.1 -Scope CurrentUser -Force | Out-Null

build_script:
  - ps: Invoke-Build -Configuration Release

test:
  assemblies:
    - Microsoft.PowerShell.EditorServices.Test.dll
    - Microsoft.PowerShell.EditorServices.Test.Protocol.dll
    - Microsoft.PowerShell.EditorServices.Test.Host.dll
